### ISSUE TITLE
Box artifact appears in AMS template under Typst 0.6

### ISSUE THREAD

**Issue by jjallaire** [typst/templates#11]
When compiling the AMS sample document under Typst 0.6 a box artifact appears right below the proof:

<img width="727" alt="Screen Shot 2023-07-08 at 8 01 19 AM" src="https://github.com/typst/templates/assets/104391/6fb6b581-2aab-4d34-aae0-3baf02d06259">

Hadn't seen this artifact under previous versions of Typst (that I can recall at least).

**Comment by laurmaedje** [comment]
Do you mean the end-of-proof square on the right? If so, that's intentional.

**Comment by jjallaire** [comment]
Yes, that is what I am referring to and I didn't realize it was intentional! (sorry for the bother)
