### ISSUE TITLE
AMS template does not support math mode in title

### ISSUE THREAD

**Issue by gdahia** [typst/templates#12]
Related to https://github.com/typst/typst/issues/1623#issuecomment-1623194643

I wanted to have a `content` for the title, so it can have math in it, but the current template passes the entire title to `set document(title: title, abstract: abstract)` and gives an error because `title` should be `string`.

I am interested in extracting the plain text representation of the content for the title like mentioned in the linked issue, but I have failed to do so.

Meanwhile, do you think it would be interesting to avoid breaking compilation of titles with `content` type by doing something like
```rust
set document(title: if type(title) == "string" { title } else { none }, author: names)
```

**Comment by denkspuren** [comment]
@laurmaedje, I have a solution to this problem: To use a string or content for the title of a document, the only problem is to set the title metadata properly, which has to be of type string.

I wrote a function named `extractText` that concatenates all strings to be found in a value of type content, string or otherwise and return it. Given the function `extractText` the above mentioned line of code in `template.typ` can be written as

``` typst
set document(title: extractText(title), author: authors.map(author => author.name))
```

The helper function can be outsourced and imported or included in the template:

``` typst
#let extractText(element) = {
  if type(element) == content {
    if element == [ ] { return " " }
    return extractText(element.fields()).trim() }
  if type(element) == dictionary { return extractText(element.values()) }
  if type(element) == array {
    return element.fold("", (res, item) => res + extractText(item))
  }
  if type(element) == bool { return "" }
  return str(element)
}

#assert.eq(extractText("hey"), "hey")
#assert.eq(extractText(12), "12")
#assert.eq(extractText(12.0), "12")
#assert.eq(extractText(12.1), "12.1")
#assert.eq(extractText(false), "")
#assert.eq(extractText(version(1,2,3)), "1.2.3")
#assert.eq(extractText((1,2,3)), "123")
#assert.eq(extractText((4,(1,"Hey",12.0),(hey: 2))), "41Hey122")
#assert.eq(extractText([This is some text.]), "This is some text.")
#assert.eq(extractText([This is _some_ text.]), "This is some text.")
#assert.eq(extractText([ Is $x^2$ an _even_ Function? ]), "Is x2 an even Function?")
#assert.eq(extractText([Is $x^2$ an _even_ Function?]), "Is x2 an even Function?")
#assert.eq(extractText([[Hey] [you]]), "[Hey] [you]")
```

What do you think?

**Comment by aaron-jack-manning** [comment]
@laurmaedje If I'm not mistaken this was fixed by [this commit](https://github.com/typst/typst/commit/c1bc529986f723f8bb06feedfbdc98520763ceb9)?

**Comment by laurmaedje** [comment]
Yes. Thanks!
