### ISSUE TITLE
Mis-indented first outline entry in the default IEEE template

### ISSUE THREAD

**Issue by DhruvDh** [typst/templates#21]
### Description

When using `#outline()` to create an index for a document using the default IEEE template, the first outline entry is not indented correctly.

![Screenshot by Dropbox Capture](https://github.com/typst/typst/assets/14926467/12a6c176-5846-4253-9754-c380cca401a8)

Here, the first outline is created with `#outline(indent: false)` and the second with `#outline(indent: true)`

### Reproduction URL

https://typst.app/project/rSHTfH6hRDVZx6I9vXQMON

### Typst version

- [X] I am using the latest version of Typst

---

In https://github.com/typst/typst/issues/2940 it was shared that this is due to the `first-line-indent` setting for `par`. 

PR to fix this in a minute.

**Comment by laurmaedje** [comment]
Closing for same reason as https://github.com/typst/templates/pull/22
