### ISSUE TITLE
AMS proof square drawn over text

### ISSUE THREAD

**Issue by kg583** [typst/templates#24]
Load the AMS template and write
```typst
#proof[
  #("1"*63) 1
]
```
which yields

![image](https://github.com/typst/templates/assets/41345727/1a21c5b5-70bd-46f5-8f07-4dfa20a797ae)

**Comment by kg583** [comment]
A similar issue occurs with numbered equations:

```typst
#set math.equation(numbering: "(1)")
$ sum_(n=0)^infinity p(n)q^n = 1 + q + 2q^2 + 3q^3 + 5q^4 + 7q^5 + 11q^6 + 15q^7 + 22q^8 + 30q^9 + 42q^10 +... $
```
![image](https://github.com/typst/templates/assets/41345727/ee543c38-1b6e-458c-8b50-2f7fe7057bcc)

I have also seen this issue in the IEEE template. No overlap occurs if no template is used.

**Comment by aaron-jack-manning** [comment]
I have just been putting a non-breaking space before the square, it seems to work.
```
#let proof(body) = block(spacing: 11.5pt, {
  emph[Proof.]
  [ ] + body
  h(1fr)
  sym.space.nobreak
  $square.stroked$
})
```

**Comment by laurmaedje** [comment]
A more comprehensive fix is here: https://forum.typst.app/t/how-can-i-right-align-the-qed-symbol-after-a-proof/948

@PgBiel could you apply that to the PR as well?

**Comment by PgBiel** [comment]
On it

**Comment by aaron-jack-manning** [comment]
> A more comprehensive fix is here: https://forum.typst.app/t/how-can-i-right-align-the-qed-symbol-after-a-proof/948

@laurmaedje That solution allows the text to get very close to the QED square, much more so than things like `amsthm`. Compare for instance

```
\documentclass{article}
\usepackage{amsmath}
\usepackage{amsthm}

\begin{document}

\begin{proof}
    a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
\end{proof}

\end{document}
```

![Screenshot from 2024-10-26 12-34-42](https://github.com/user-attachments/assets/c065ac3c-82e1-4142-81cc-c2c34cc59820)

to

```
#let proof(body) = block(width: 100%, {
  [_Proof._ ]
  body
  h(1fr)
  sym.wj
  $qed$
})

#proof[
  a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
]
```
![Screenshot from 2024-10-26 12-35-49](https://github.com/user-attachments/assets/eefecae0-3698-470f-a797-5ee7124bed1e)

When reducing the number of `a`s in the LaTeX example by one, the spacing is adjusted to keep the same distance between the QED symbol and the last one.

The text being so close to the QED symbol, to my eye, looks a little off, and also is quite different to AMS templates. I put a non-breaking space in to solve this but perhaps with a better understanding of how typst works you can think of something better.

**Comment by PgBiel** [comment]
I think the solution with `box(width: 0pt)` before `h(1fr)` could be adapted for that purpose, using e.g. `box(width: 3pt)` instead. cc @laurmaedje

**Comment by aaron-jack-manning** [comment]
@PgBiel This forces the square to the next line though. The square should be on the same line that the text ends on.
```
#let proof(body) = block(width: 100%, {
  [_Proof._ ]
  body
  box(width: 0pt)
  h(1fr)
  sym.wj
  $qed$
})

#proof[
  a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
]
```

![Screenshot from 2024-10-27 08-28-39](https://github.com/user-attachments/assets/98902cbc-dd66-4d4c-9ad9-31868bd5fe70)

The typical desired behavior, and what `amsthm` does, is to always keep the QED symbol on the same line and thus if it won't fit, force a word to the next line and shuffle the square down with it.

![Screenshot from 2024-10-27 08-32-50](https://github.com/user-attachments/assets/1823b9a7-8e89-4f37-84af-38769b0c6a0b)

If you fiddle with the LaTeX example and change the number of `a`s, you will see that the place for the square with a little spacing to its left is almost "pre-allocated" so that the spacing between words will adjust to make it fit, and only when it can't fit will a whole word end up on the next line.

**Comment by aaron-jack-manning** [comment]
How about this?
```
#let proof(body) = block(spacing: 11.5pt, {
  emph[Proof.]
  [ ] + body
  h(1fr)
  sym.wj
  sym.space.nobreak
  $square.stroked$
})
``` 
Forcing the last preceding word  to the next line is the desired behavior (or at least it is what most LaTeX proof environments seem to do), but the amount of space next to the QED symbol isn't quite right. So why not just force a bit of extra spacing there?
