### ISSUE TITLE
How do you develop themes?

### ISSUE THREAD

**Issue by domoritz** [typst/templates#25]
As someone who wants to develop their own theme, can you share how you develop locally? I see that you have sub-folders with a template but that one refers to the published package. Is there a simple way to refer to/register a template or package with typst during development?

**Comment by laurmaedje** [comment]
See here: https://github.com/typst/packages#local-packages

**Comment by laurmaedje** [comment]
If you have any further question, best to open a [GitHub discussion on typst/typst](https://github.com/typst/typst/discussions) or to ask on our [Discord server](https://discord.gg/2uDybryKPe).

**Comment by domoritz** [comment]
Thanks for the pointer. I ended up writing a script to link the current directory to a local package: https://github.com/domoritz/tvcg-journal-typst/blob/e7eb9af704b0ce40157f596a84021f1052adc9e5/link.sh. It feels a bit ad-hoc and it would be nice to have some cleaner/built in way to develop locally. I'll use the workflow for now and will start a discussion once I learn more.
