### ISSUE TITLE
ACL Conferences Template

### ISSUE THREAD

**Issue by danielfleischer** [typst/templates#33]
Hi! would you consider creating a template for ACL conferences, based on https://github.com/acl-org/acl-style-files? thanks!

**Comment by danielfleischer** [comment]
I'm working on one myself, can close. Watching https://github.com/typst/typst/issues/352 (line numbers in margin for reviewers).

**Comment by laurmaedje** [comment]
We hope to ship line numbers in the next release. :)

**Comment by laurmaedje** [comment]
No PR yet, but our team member @PgBiel has just started working on it. We've also opened a [general discussion thread]((https://discord.com/channels/1054443721975922748/1257705582991900703/1257705582991900703)) about Academic requirements on our Discord server.

**Comment by kescobo** [comment]
> e've also opened a general discussion thread about Academic requirements on our Discord server.

Nice! https://discord.com/channels/1054443721975922748/1257705582991900703/1257705582991900703

**Comment by pjox** [comment]
Hi @danielfleischer, did you ever release your Typst template for ACL conferences? I am interested if you did, but I was not able to find it

**Comment by alexanderkoller** [comment]
I just discovered this thread - let me point you to [tracl](https://typst.app/universe/package/tracl). We're planning to release version 0.8.0 this month.

**Comment by danielfleischer** [comment]
Indeed, I've used it, it's great!
