### ISSUE TITLE
IEEE: Wrong indent after equation without following text.

### ISSUE THREAD

**Issue by RomeoV** [typst/templates#37]
Consider the following screenshot (only left column of IEEE format is shown, thus title looks weird).
![screenshot_2024-05-31T19:25:35UTC](https://github.com/typst/templates/assets/8644490/f127141c-9aae-4e4d-ad2a-7abdf9e0e5f6)

After a full-line equation, typst will not indent a new paragraph correctly (as seen in red).
The indentation works however if the equation is followed by some text (as seen in blue).

The code is below. This is on `typst 0.11.1` (online editor).

```typst
#import "@preview/charged-ieee:0.1.0": ieee
#show: ieee.with( title: [My title], )
= Section 1
#lorem(15)
$ a=1. $
#text(blue)[This text is necessary to fix indent of next paragraph.]

#text(blue)[This is a new paragraph. There #emph[is] indent here.]

= Section 1
#lorem(15)
$ a=1. $

#text(red)[This is a new paragraph. There is #emph[no] indent here, but there should be!]
```

**Comment by laurmaedje** [comment]
This is not specific to the IEEE template, but rather a general limitation of Typst. See typst/typst#311. We hope to resolve it soon.
