### ISSUE TITLE
running charged-ieee locally

### ISSUE THREAD

**Issue by navh** [typst/templates#45]
When I use

`#import "@preview/charged-ieee:0.1.0": ieee`

[main.pdf](https://github.com/user-attachments/files/16549158/main.pdf)

I get a document that is almost correct, but with some strange differences from the template in this repo. The abstract is not bold, and appears to be 10pt font. The title is larger.

When I copy-paste the .lib file into my own project and use

`#import "lib.typ": ieee`

[main.pdf](https://github.com/user-attachments/files/16549180/main.pdf)

Everything seems to work exactly as expected. 

I have all TeX Gyre fonts installed locally.

**Comment by laurmaedje** [comment]
The template hasn't been released in a while. The version in this repo is different from 0.1.0.

**Comment by laurmaedje** [comment]
I've opened a PR to update it: https://github.com/typst/packages/pull/869
