### ISSUE TITLE
Standard fiction book header

### ISSUE THREAD

**Issue by acestronautical** [typst/templates#51]
The most common fiction book running header is:

left corner: even pageno,  left center: author italics,  right center: book title, right corner: odd pageno

It would be great if you could support this format

**Comment by aaron-jack-manning** [comment]
This is not too hard to do, here are the necessary changes: b3b5d05ee955098910eed4764c13ce94e8d85c70. I have also seen the left side title and right side heading frequently.

I'll make a PR if this is desired by the maintainers, although I suspect having a few configurable options is most preferable, and then we can bike-shed about what should be the default later.

**Comment by laurmaedje** [comment]
@aaron-jack-manning Feel free to make a PR
