### ISSUE TITLE
Header and Footer logic seems broken for Typst v0.12 

### ISSUE THREAD

**Issue by ckunte** [typst/templates#56]
The custom header and footer logic for the template code below in the [wonderous book](https://github.com/typst/templates/tree/main/wonderous-book) seems broken in Typst v0.12.

The warnings received are as below:
1. warning: `locate` with callback function is deprecated
2. warning: calling `query` with a location is deprecated

```rust
  // Configure page properties.
  set page(
    numbering: "1",

    // The header always contains the book title on odd pages and
    // the chapter title on even pages, unless the page is one
    // the starts a chapter (the chapter title is obvious then).
    header: locate(loc => {
      // Are we on an odd page?
      let i = counter(page).at(loc).first()
      if calc.odd(i) {
        return text(0.95em, smallcaps(title))
      }

      // Are we on a page that starts a chapter? (We also check
      // the previous page because some headings contain pagebreaks.)
      let all = query(heading, loc)
      if all.any(it => it.location().page() in (i - 1, i)) {
        return
      }

      // Find the heading of the section we are currently in.
      let before = query(selector(heading).before(loc), loc)
      if before != () {
        align(right, text(0.95em, smallcaps(before.last().body)))
      }
    }),
  )
```
The first part seems easy to replace:
```rust
    header: context {
      let i = counter(page).get().first() 
      // Are we on a page other than the first?
      if calc.odd(i) {
        return text(0.95em, smallcaps(title))
      }
```
I am finding it harder to update the other two (i.e. chapter start, and finding heading section currently in. Appreciate if the lib.typ is updated to v0.12. Thank you.

**Comment by laurmaedje** [comment]
We are in the process of updating the templates for Typst 0.12, but not yet completely done (see also the open PRs).

**Comment by ckunte** [comment]
> We are in the process of updating the templates for Typst 0.12, but not yet completely done (see also the open PRs).

I am grateful for the pointer, @laurmaedje. I was able to use @PgBiel's [PR](https://github.com/typst/templates/pull/55/commits/45012f083205d5beb2383f1ab5f621f83412331f) successfully to reproduce the old functionality.
