### ISSUE TITLE
ams template: references to theorem labels don't include the heading

### ISSUE THREAD

**Issue by WannesMalfait** [typst/templates#8]
The heading number is included in the theorem itself, but not when you reference it. The numbering should be consistent.

Example based on `main.typ` in the ams template:
```typ
#theorem[
  The square of any real number is non-negative.
]<thm:sq-positive>

#proof[
  Any real number $x$ satisfies $x > 0$, $x = 0$, or $x < 0$. If $x = 0$,
  then $x^2 = 0 >= 0$. If $x > 0$ then as a positive time a positive is
  positive we have $x^2 = x x > 0$. If $x < 0$ then $−x > 0$ and so by
  what we have just done $x^2 = (−x)^2 > 0$. So in all cases $x^2 ≥ 0$.
]

= Introduction

#theorem[
    For any right-angled triangle with legs $a,b$ and hypotenuse $c$:
    $
    a^2 + b^2 = c^2
    $
]
<thm:pythagoras>

This is a new section.
We now use @thm:sq-positive
and @thm:pythagoras
```
![image](https://github.com/typst/templates/assets/46323945/80a714f5-962e-4a74-967b-1ea83e2a4255)

**Comment by YDX-2147483647** [comment]
I have the same issue with `table`.

Maybe we should change the following lines…

https://github.com/typst/templates/blob/7cec678fb6a6782361c79f3ac87c41a8a2b4a0a2/ams/template.typ#L151-L154

…to…

```typst
      smallcaps(it.supplement)
      if it.numbering != none {
        [ #it.counter.display(it.numbering)]
      }
```

Relevant: The example of _modifying the appearance_ in [Figure Function – Typst Documentation](https://typst.app/docs/reference/meta/figure/#modifying-appearance).

**Comment by YDX-2147483647** [comment]
I apologize to you… It's hard than I thought.

1. #10 is the first step, and is done.

2. Now the theorem counter does not even count the heading — it's only displayed.

   https://github.com/typst/templates/blob/7cec678fb6a6782361c79f3ac87c41a8a2b4a0a2/ams/template.typ#L168-L169

   The counter is reset when a new chapter starts.

   https://github.com/typst/templates/blob/7cec678fb6a6782361c79f3ac87c41a8a2b4a0a2/ams/template.typ#L115

   To fix that, we should turn it into a multi-level counter. It's possible, but I don't know how to start…

**Comment by laurmaedje** [comment]
I can't reproduce this issue. If an issue remains, please open a new one. We could also consider porting the AMS template from its own theorem handling to one of the packages.
